### ISSUE TITLE
Sorted set is not calling the correct method for some set operations

### ISSUE THREAD

**Issue by khun84** [nateware/redis-objects#221]
gem `redis-objects` version: 1.3.1
gem `redis` version: 3.3.3

Im have defined 2 sorted set and tried to perform intersect and union operations on sorted_set. However the set operations threw me an error of `Redis::CommandError: ERR unknown command 'zinter'`

Reproducing steps:
```ruby
zs1 = Redis::SortedSet.new('zset1')
zs1.add('a', 1)
zs2 = Redis::SortedSet.new('zset2')
zs2.add('a', 2)

zs1 & zs2
```

Error details:
```
Redis::CommandError: ERR unknown command 'zinter'
	from /Users/Daniel/.rvm/gems/ruby-2.3.1/gems/redis-3.3.3/lib/redis/client.rb:121:in `call'
	from /Users/Daniel/.rvm/gems/ruby-2.3.1/gems/redis-3.3.3/lib/redis.rb:2705:in `block in method_missing'
	from /Users/Daniel/.rvm/gems/ruby-2.3.1/gems/redis-3.3.3/lib/redis.rb:58:in `block in synchronize'
	from /Users/Daniel/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /Users/Daniel/.rvm/gems/ruby-2.3.1/gems/redis-3.3.3/lib/redis.rb:58:in `synchronize'
	from /Users/Daniel/.rvm/gems/ruby-2.3.1/gems/redis-3.3.3/lib/redis.rb:2704:in `method_missing'
	from /Users/Daniel/.rvm/gems/ruby-2.3.1/gems/redis-objects-1.3.1/lib/redis/sorted_set.rb:211:in `intersection'
	from (irb):32
	from /Users/Daniel/.rvm/gems/ruby-2.3.1/gems/railties-5.0.6/lib/rails/commands/console.rb:65:in `start'
	from /Users/Daniel/.rvm/gems/ruby-2.3.1/gems/railties-5.0.6/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/Daniel/.rvm/gems/ruby-2.3.1/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/Daniel/.rvm/gems/ruby-2.3.1/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/Daniel/.rvm/gems/ruby-2.3.1/gems/railties-5.0.6/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

I opened the redis-objects gem file and found out that the redis-objects sorted set `intersection` was implemented by calling `redis.zinter`. However, the underlying `redis` sorted set intersection method signature was `zintersection` instead.

Am I missing something in any config or module loading?

**Comment by nateware** [comment]
This patch was merged. Thanks!
