### ISSUE TITLE
Redis.current depreciated.

### ISSUE THREAD

**Issue by xorgnak** [nateware/redis-objects#271]
gem breaks because of breaking change to redis gem.

**Comment by gaj23** [comment]
+1 to this

I'm using redis v6.2
I'm using redis-objects v1.7.0

When running my tests, I see the following error (I've provided only a partial stack trace):

```ruby
NoMethodError:
       undefined method `current' for Redis:Class

               @redis || $redis || Redis.current ||
                                        ^^^^^^^^
     # /data/bundle/ruby/3.1.0/gems/redis-objects-1.7.0/lib/redis/objects.rb:65:in `redis'
     # /data/bundle/ruby/3.1.0/gems/redis-objects-1.7.0/lib/redis/base_object.rb:18:in `redis'
     # /data/bundle/ruby/3.1.0/gems/redis-objects-1.7.0/lib/redis/value.rb:21:in `value'
```

I tried using v2.0.0alpha to the same result. 

_I cannot upgrade redis due to this._

**Comment by nateware** [comment]
Please try locking to version `2.0.0.beta` which I just pushed to rubygems
